install.packages("dagitty",repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("rstan", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("ggdag",repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("ggridges",repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("brms", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("tidyverse", repos = "https://cloud.r-project.org/", dependencies=TRUE)
install.packages("nycflights13",repos = "https://cloud.r-project.org/", dependencies=TRUE)
